kana = {
"Ha" : ("あ", "a"),
"Hi" : ("い", "i"),
"Hu" : ("う", "u"),
"He" : ("え", "e"),
"Ho" : ("お", "o"),
"Hka" : ("か", "ka"),
"Hki" : ("き", "ki"),
"Hku" : ("く", "ku"),
"Hke" : ("け", "ke"),
"Hko" : ("こ", "ko"),
"Hkya" : ("きゃ", "kya"),
"Hkyu" : ("きゅ", "kyu"),
"Hkyo" : ("きょ", "kyo"),
"Hsa" : ("さ", "sa"),
"Hshi" : ("し", "shi"),
"Hsu" : ("す", "su"),
"Hse" : ("せ", "se"),
"Hso" : ("そ", "so"),
"Hsha" : ("しゃ", "sha"),
"Hshu" : ("しゅ", "shu"),
"Hsho" : ("しょ", "sho"),
"Hta" : ("た", "ta"),
"Hchi" : ("ち", "chi"),
"Htsu" : ("つ", "tsu"),
"Hte" : ("て", "te"),
"Hto" : ("と", "to"),
"Hcha" : ("ちゃ", "cha"),
"Hchu" : ("ちゅ", "chu"),
"Hcho" : ("ちょ", "cho"),
"Hna" : ("な", "na"),
"Hni" : ("に", "ni"),
"Hnu" : ("ぬ", "nu"),
"Hne" : ("ね", "ne"),
"Hno" : ("の", "no"),
"Hnya" : ("にゃ", "nya"),
"Hnyu" : ("にゅ", "nyu"),
"Hnyo" : ("にょ", "nyo"),
"Hha" : ("は", "ha", "wa"),
"Hhi" : ("ひ", "hi"),
"Hfu" : ("ふ", "fu"),
"Hhe" : ("へ", "he", "e"),
"Hho" : ("ほ", "ho"),
"Hhya" : ("ひゃ", "hya"),
"Hhyu" : ("ひゅ", "hyu"),
"Hhyo" : ("ひょ", "hyo"),
"Hma" : ("ま", "ma"),
"Hmi" : ("み", "mi"),
"Hmu" : ("む", "mu"),
"Hme" : ("め", "me"),
"Hmo" : ("も", "mo"),
"Hmya" : ("みゃ", "mya"),
"Hmyu" : ("みゅ", "myu"),
"Hmyo" : ("みょ", "myo"),
"Hya" : ("や", "ya"),
"Hyu" : ("ゆ", "yu"),
"Hyo" : ("よ", "yo"),
"Hra" : ("ら", "ra"),
"Hri" : ("り", "ri"),
"Hru" : ("る", "ru"),
"Hre" : ("れ", "re"),
"Hro" : ("ろ", "ro"),
"Hrya" : ("りゃ", "rya"),
"Hryu" : ("りゅ", "ryu"),
"Hryo" : ("りょ", "ryo"),
"Hwa" : ("わ", "wa"),
"Hwo" : ("を", "o", "wo"),
"Hga" : ("が", "ga"),
"Hgi" : ("ぎ", "gi"),
"Hgu" : ("ぐ", "gu"),
"Hge" : ("げ", "ge"),
"Hgo" : ("ご", "go"),
"Hgya" : ("ぎゃ", "gya"),
"Hgyu" : ("ぎゅ", "gyu"),
"Hgyo" : ("ぎょ", "gyo"),
"Hza" : ("ざ", "za"),
"Hji" : ("じ", "ji"),
"Hzu" : ("ず", "zu"),
"Hze" : ("ぜ", "ze"),
"Hzo" : ("ぞ", "zo"),
"Hja" : ("じゃ", "ja"),
"Hju" : ("じゅ", "ju"),
"Hjo" : ("じょ", "jo"),
"Hda" : ("だ", "da"),
"Hdji" : ("ぢ", "ji"),
"Hdzu" : ("づ", "zu"),
"Hde" : ("で", "de"),
"Hdo" : ("ど", "do"),
"Hba" : ("ば", "ba"),
"Hbi" : ("び", "bi"),
"Hbu" : ("ぶ", "bu"),
"Hbe" : ("べ", "be"),
"Hbo" : ("ぼ", "bo"),
"Hbya" : ("びゃ", "bya"),
"Hbyu" : ("びゅ", "byu"),
"Hbyo" : ("びょ", "byo"),
"Hpa" : ("ぱ", "pa"),
"Hpi" : ("ぴ", "pi"),
"Hpu" : ("ぷ", "pu"),
"Hpe" : ("ぺ", "pe"),
"Hpo" : ("ぽ", "po"),
"Hpya" : ("ぴゃ", "pya"),
"Hpyu" : ("ぴゅ", "pyu"),
"Hpyo" : ("ぴょ", "pyo"),
"Hn" : ("ん", "n"),
"Ka" : ("ア", "a"),
"Ki" : ("イ", "i"),
"Ku" : ("ウ", "u"),
"Ke" : ("エ", "e"),
"Ko" : ("オ", "o"),
"Kka" : ("カ", "ka"),
"Kki" : ("キ", "ki"),
"Kku" : ("ク", "ku"),
"Kke" : ("ケ", "ke"),
"Kko" : ("コ", "ko"),
"Kkya" : ("キャ", "kya"),
"Kkyu" : ("キュ", "kyu"),
"Kkyo" : ("キョ", "kyo"),
"Ksa" : ("サ", "sa"),
"Kshi" : ("シ", "shi"),
"Ksu" : ("ス", "su"),
"Kse" : ("セ", "se"),
"Kso" : ("ソ", "so"),
"Ksha" : ("シャ", "sha"),
"Kshu" : ("シュ", "shu"),
"Ksho" : ("ショ", "sho"),
"Kta" : ("タ", "ta"),
"Kchi" : ("チ", "chi"),
"Ktsu" : ("ツ", "tsu"),
"Kte" : ("テ", "te"),
"Kto" : ("ト", "to"),
"Kcha" : ("チャ", "cha"),
"Kchu" : ("チュ", "chu"),
"Kcho" : ("チョ", "cho"),
"Kna" : ("ナ", "na"),
"Kni" : ("ニ", "ni"),
"Knu" : ("ヌ", "nu"),
"Kne" : ("ネ", "ne"),
"Kno" : ("ノ", "no"),
"Knya" : ("ニャ", "nya"),
"Knyu" : ("ニュ", "nyu"),
"Knyo" : ("ニョ", "nyo"),
"Kha" : ("ハ", "ha"),
"Khi" : ("ヒ", "hi"),
"Kfu" : ("フ", "fu"),
"Khe" : ("ヘ", "he"),
"Kho" : ("ホ", "ho"),
"Khya" : ("ヒャ", "hya"),
"Khyu" : ("ヒュ", "hyu"),
"Khyo" : ("ヒョ", "hyo"),
"Kma" : ("マ", "ma"),
"Kmi" : ("ミ", "mi"),
"Kmu" : ("ム", "mu"),
"Kme" : ("メ", "me"),
"Kmo" : ("モ", "mo"),
"Kmya" : ("ミャ", "mya"),
"Kmyu" : ("ミュ", "myu"),
"Kmyo" : ("ミョ", "myo"),
"Kya" : ("ヤ", "ya"),
"Kyu" : ("ユ", "yu"),
"Kyo" : ("ヨ", "yo"),
"Kra" : ("ラ", "ra"),
"Kri" : ("リ", "ri"),
"Kru" : ("ル", "ru"),
"Kre" : ("レ", "re"),
"Kro" : ("ロ", "ro"),
"Krya" : ("リャ", "rya"),
"Kryu" : ("リュ", "ryu"),
"Kryo" : ("リョ", "ryo"),
"Kwa" : ("ワ", "wa"),
"Kwo" : ("ヲ", "o", "wo"),
"Kga" : ("ガ", "ga"),
"Kgi" : ("ギ", "gi"),
"Kgu" : ("グ", "gu"),
"Kge" : ("ゲ", "ge"),
"Kgo" : ("ゴ", "go"),
"Kgya" : ("ギャ", "gya"),
"Kgyu" : ("ギュ", "gyu"),
"Kgyo" : ("ギョ", "gyo"),
"Kza" : ("ザ", "za"),
"Kji" : ("ジ", "ji"),
"Kzu" : ("ズ", "zu"),
"Kze" : ("ゼ", "ze"),
"Kzo" : ("ゾ", "zo"),
"Kja" : ("ジャ", "ja"),
"Kju" : ("ジュ", "ju"),
"Kjo" : ("ジョ", "jo"),
"Kda" : ("ダ", "da"),
"Kdji" : ("ヂ", "ji"),
"Kdzu" : ("ヅ", "zu"),
"Kde" : ("デ", "de"),
"Kdo" : ("ド", "do"),
"Kba" : ("バ", "ba"),
"Kbi" : ("ビ", "bi"),
"Kbu" : ("ブ", "bu"),
"Kbe" : ("ベ", "be"),
"Kbo" : ("ボ", "bo"),
"Kbya" : ("ビャ", "bya"),
"Kbyu" : ("ビュ", "byu"),
"Kbyo" : ("ビョ", "byo"),
"Kpa" : ("パ", "pa"),
"Kpi" : ("ピ", "pi"),
"Kpu" : ("プ", "pu"),
"Kpe" : ("ペ", "pe"),
"Kpo" : ("ポ", "po"),
"Kpya" : ("ピャ", "pya"),
"Kpyu" : ("ピュ", "pyu"),
"Kpyo" : ("ピョ", "pyo"),
"Kn" : ("ン", "n")
}


hiragana = {
"Ha",  "Hi",   "Hu",   "He",  "Ho",
"Hka", "Hki",  "Hku",  "Hke", "Hko", "Hkya", "Hkyu", "Hkyo",
"Hsa", "Hshi", "Hsu",  "Hse", "Hso", "Hsha", "Hshu", "Hsho",
"Hta", "Hchi", "Htsu", "Hte", "Hto", "Hcha", "Hchu", "Hcho",
"Hna", "Hni",  "Hnu",  "Hne", "Hno", "Hnya", "Hnyu", "Hnyo",
"Hha", "Hhi",  "Hfu",  "Hhe", "Hho", "Hhya", "Hhyu", "Hhyo",
"Hma", "Hmi",  "Hmu",  "Hme", "Hmo", "Hmya", "Hmyu", "Hmyo",
"Hya",         "Hyu",         "Hyo",
"Hra", "Hri",  "Hru",  "Hre", "Hro", "Hrya", "Hryu", "Hryo",
"Hwa",                        "Hwo",
"Hga", "Hgi",  "Hgu",  "Hge", "Hgo", "Hgya", "Hgyu", "Hgyo",
"Hza", "Hji",  "Hzu",  "Hze", "Hzo", "Hja",  "Hju",  "Hjo",
"Hda", "Hdji", "Hdzu", "Hde", "Hdo",
"Hba", "Hbi",  "Hbu",  "Hbe", "Hbo", "Hbya", "Hbyu", "Hbyo",
"Hpa", "Hpi",  "Hpu",  "Hpe", "Hpo", "Hpya", "Hpyu", "Hpyo",
"Hn"
}

katakana = {
"Ka",  "Ki",   "Ku",   "Ke",  "Ko",
"Kka", "Kki",  "Kku",  "Kke", "Kko", "Kkya", "Kkyu", "Kkyo",
"Ksa", "Kshi", "Ksu",  "Kse", "Kso", "Ksha", "Kshu", "Ksho",
"Kta", "Kchi", "Ktsu", "Kte", "Kto", "Kcha", "Kchu", "Kcho",
"Kna", "Kni",  "Knu",  "Kne", "Kno", "Knya", "Knyu", "Knyo",
"Kha", "Khi",  "Kfu",  "Khe", "Kho", "Khya", "Khyu", "Khyo",
"Kma", "Kmi",  "Kmu",  "Kme", "Kmo", "Kmya", "Kmyu", "Kmyo",
"Kya",         "Kyu",         "Kyo",
"Kra", "Kri",  "Kru",  "Kre", "Kro", "Krya", "Kryu", "Kryo",
"Kwa",                        "Kwo",
"Kga", "Kgi",  "Kgu",  "Kge", "Kgo", "Kgya", "Kgyu", "Kgyo",
"Kza", "Kji",  "Kzu",  "Kze", "Kzo", "Kja",  "Kju",  "Kjo",
"Kda", "Kdji", "Kdzu", "Kde", "Kdo",
"Kba", "Kbi",  "Kbu",  "Kbe", "Kbo", "Kbya", "Kbyu", "Kbyo",
"Kpa", "Kpi",  "Kpu",  "Kpe", "Kpo", "Kpya", "Kpyu", "Kpyo",
"Kn"
}

basic = {
"Ha",  "Hi",   "Hu",   "He",  "Ho",
"Hka", "Hki",  "Hku",  "Hke", "Hko",
"Hsa", "Hshi", "Hsu",  "Hse", "Hso",
"Hta", "Hchi", "Htsu", "Hte", "Hto",
"Hna", "Hni",  "Hnu",  "Hne", "Hno",
"Hha", "Hhi",  "Hfu",  "Hhe", "Hho",
"Hma", "Hmi",  "Hmu",  "Hme", "Hmo",
"Hya",         "Hyu",         "Hyo",
"Hra", "Hri",  "Hru",  "Hre", "Hro",
"Hwa",                        "Hwo",
"Hn",
"Ka",  "Ki",   "Ku",   "Ke",  "Ko",
"Kka", "Kki",  "Kku",  "Kke", "Kko",
"Ksa", "Kshi", "Ksu",  "Kse", "Kso",
"Kta", "Kchi", "Ktsu", "Kte", "Kto",
"Kna", "Kni",  "Knu",  "Kne", "Kno",
"Kha", "Khi",  "Kfu",  "Khe", "Kho",
"Kma", "Kmi",  "Kmu",  "Kme", "Kmo",
"Kya",         "Kyu",         "Kyo",
"Kra", "Kri",  "Kru",  "Kre", "Kro",
"Kwa",                        "Kwo",
"Kn"
}

diacritic = {
"Hga", "Hgi",  "Hgu",  "Hge", "Hgo", "Hgya", "Hgyu", "Hgyo",
"Hza", "Hji",  "Hzu",  "Hze", "Hzo", "Hja",  "Hju",  "Hjo",
"Hda", "Hdji", "Hdzu", "Hde", "Hdo",
"Hba", "Hbi",  "Hbu",  "Hbe", "Hbo", "Hbya", "Hbyu", "Hbyo",
"Hpa", "Hpi",  "Hpu",  "Hpe", "Hpo", "Hpya", "Hpyu", "Hpyo",
"Kga", "Kgi",  "Kgu",  "Kge", "Kgo", "Kgya", "Kgyu", "Kgyo",
"Kza", "Kji",  "Kzu",  "Kze", "Kzo", "Kja",  "Kju",  "Kjo",
"Kda", "Kdji", "Kdzu", "Kde", "Kdo",
"Kba", "Kbi",  "Kbu",  "Kbe", "Kbo", "Kbya", "Kbyu", "Kbyo",
"Kpa", "Kpi",  "Kpu",  "Kpe", "Kpo", "Kpya", "Kpyu", "Kpyo"
}

digraph = {
"Hkya", "Hkyu", "Hkyo",
"Hsha", "Hshu", "Hsho",
"Hcha", "Hchu", "Hcho",
"Hnya", "Hnyu", "Hnyo",
"Hhya", "Hhyu", "Hhyo",
"Hmya", "Hmyu", "Hmyo",
"Hrya", "Hryu", "Hryo",
"Hgya", "Hgyu", "Hgyo",
"Hja",  "Hju",  "Hjo",
"Hbya", "Hbyu", "Hbyo",
"Hpya", "Hpyu", "Hpyo",
"Kkya", "Kkyu", "Kkyo",
"Ksha", "Kshu", "Ksho",
"Kcha", "Kchu", "Kcho",
"Knya", "Knyu", "Knyo",
"Khya", "Khyu", "Khyo",
"Kmya", "Kmyu", "Kmyo",
"Krya", "Kryu", "Kryo",
"Kgya", "Kgyu", "Kgyo",
"Kja",  "Kju",  "Kjo",
"Kbya", "Kbyu", "Kbyo",
"Kpya", "Kpyu", "Kpyo"
}


# TODO: Add support for archaic/obsolete/uncommonn kana, extended katakana
